# Generated by Django 5.2 on 2025-04-26 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chat_message_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_highlighted',
            field=models.BooleanField(default=False),
        ),
    ]
